### ISSUE TITLE
Decide how to store state

### ISSUE THREAD

**Issue by k-nut** [freifunk-berlin/ca.berlin.freifunk.net#1]
We need to decide on a way how we want to mark Requests as worked on. 

The two main options would be:
- check if we have a vpn file with this name already
- store the fact that a certificate was generated it in the database

I propose following the second options since that will enable us to do something like `for request in Request.query.filter_by(generation_date!=None).all():` Then we would just update the records for which we have generated certificates with the `generation_date` and not query those again the next time. An alternative would be to just use a boolean to store if the certificate has been generated already but I think we could just as well store the date of the generation for better transparency.

I just added a prompt in the `buildcert.py` that asks for confirmation before generating each certificate. The question would be what to do when confirmation is not given.  Options are:
- Also set `generation_date` / boolean but don't generate a certificate
- Simply skip the Request and be asked again next time
- Delete it from the database
- Add another field to the database that says this one was skipped and also filter those out

What do you think? Feedback is much appreciated.

**Comment by booo** [comment]
I'm fine with the idea of storing the state in the database. We should implement this with a generateion_date so we can inform users in 10 years about the invalid cert they have. If we do an initial import of existing certs we should extract the date of creation.

We should just skip the request and write another minimal script that removes a request from the database.

**Comment by k-nut** [comment]
Ok, I will add that to the model and buildcert.

**Comment by k-nut** [comment]
This is implemented in https://github.com/freifunk-berlin/ca.berlin.freifunk.net/commit/37aad83f067947602552dc9c5e50a892361b63e4

**Comment by booo** [comment]
Very nice. Should we create another ticket for the import script?

**Comment by k-nut** [comment]
Yes please. If you can provide the current file structure I can write a script to import those.

**Comment by booo** [comment]
I think this is done so I'm closing this.
