### ISSUE TITLE
integrate buildcert.py and import.py into manage.py

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/ca.berlin.freifunk.net#14]
We should integrate buildcert.py and import.py as commands into the manage.py file.

**Comment by SvenRoederer** [comment]
@booo this is a half finished rework of the buildcert.py (https://github.com/freifunk-berlin/ca.berlin.freifunk.net/compare/master...SvenRoederer:feature/pyOpenSSL?expand=1)
- it builds a new client certificate which is identically to the current ones
- generating of the .tgz has to be implemented

following open issues:
- this code needs to access the CA-key; are there any constraints? 
- we need to set a Serialnumber (cert.set_serial_number) which is currently hardcoded to 1000 is the database providing such id? is the "id"-key numerical?

**Comment by booo** [comment]
I think building a tool that solves our specific "problem" that has clean code and is small is a good idea.

Generating a archive should not be a problem with https://docs.python.org/3/library/archiving.html

The code should maybe only load the CA-key for the time of certificate generation and then unload the data? I don't see other problems.

The serial number is currently stored in a file called "serial?" in /etc/openvpn/easy-rsa or something.

**Comment by SvenRoederer** [comment]
isn' it better to also drop any dependency to easy-rsa? esp. when it's only needed to tracking the cert-serial?
Any concerns in adding a auto-id field to the database which keeps the SN for each client-cert? This requires a migration-skript 
- to set the serial-field to a unassigned SN
- maybe to import the currently assigned SNs

**Comment by booo** [comment]
@KenTacki integrated the buildcert.py functionality as subcommand into the manage.py programm.

**Comment by SvenRoederer** [comment]
Have seen this. I can port the former code #37 to the updated module

**Comment by SvenRoederer** [comment]
Since some time the ```buildcert.py``` is gone. 
I don't think that it's valuable to invest energy in integrating ```import.py``` also into the main-code. As the import will only be done max. once by any instance. Feels to me like wasting time...

**Comment by bobster-galore** [comment]
Is this interesting again because of prolongation of community-tunnel-certs?

**Comment by SvenRoederer** [comment]
@bobster-galore for prolonging there is already https://github.com/freifunk-berlin/ca.berlin.freifunk.net/issues/57 which provides a basic function for this

**Comment by SvenRoederer** [comment]
I'm fine with closing this, as I think we can ignore "import.py" (https://github.com/freifunk-berlin/ca.berlin.freifunk.net/issues/14#issuecomment-352287323)
