### ISSUE TITLE
check for id regex

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/ca.berlin.freifunk.net#18]
It seems like the regex supports e.g. underscores. I'm not sure why. We should double check this!

**Comment by k-nut** [comment]
Are you referring to this one? https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/app.py#L47 That would be `[a-z]+[\-a-z]*`. I don't see why that would allow underscores. Why do you think this?

**Comment by booo** [comment]
Yes, I'm talking about this regex. I opened this ticket because I see things like foo-bar/baz_biz in the database.

**Comment by k-nut** [comment]
That seems like a wonderful use case for a new test. I guess we only need to refactor a little first to get the test setup working and then we can add a test that tries to register something with a name that contains an underscore.

**Comment by booo** [comment]
Do you have the time to do this? Do you need any help?

**Comment by k-nut** [comment]
I just created a test for this. It is failing but I still do not understand why. The length validation seems to work, the regex does not... https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/tests/test.py#L79
