### ISSUE TITLE
Regex doesn't allow numbers but example contains numbers

### ISSUE THREAD

**Issue by drscream** [freifunk-berlin/ca.berlin.freifunk.net#21]
The regular expression which check the ID does not allow numbers (https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/app.py#L47). But the example text contains numbers:

> Ein kurzer und eindeutiger Name für deinen Zugang (z.B. funkenpumpe oder hermannstr42_vh). Bitte nur Kleinbuchstaben und Bindestriche verwenden.

The same issue is the underscore in the example, which is not allowed based on the error message displayed:

> Must be lowercase and can contain '-'

I'm not sure if the example text is wrong or the regex so I didn't open a pull request yet.

**Comment by ffcb** [comment]
the examples were changed 7 days ago (https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/templates/index.html)
to fit the new text i created the pullrequest https://github.com/freifunk-berlin/ca.berlin.freifunk.net/pull/30 to update the validator

**Comment by booo** [comment]
Should be fixed with the latest merge. Thanks @ffcb for the implementation!
