### ISSUE TITLE
Weekly digest auf Mailingliste

### ISSUE THREAD

**Issue by monic2001** [freifunk-berlin/ca.berlin.freifunk.net#27]
Ein weekly digest der neuen Subscriber/Knoten inkl. Kommentar, warum sie nen freifunk VPN möchten, wäre ein tolles soziales feature, was durch den Umbau verloren ging.

**Comment by booo** [comment]
@k-nut und ich, schlagen vor das Feature in eine Kartenanwendung einzubauen und Router-Verwalter_innen in der Umgebung über einen neuen Knoten zu informieren, wenn Sie dies wünschen. Die Verwalter_innen könnten z.B. im Wizard oder owm-Script mitangeben, ob Sie über neue Router im Umkreis von X Meter per z.B. Mail informiert werden wollen.

Ich denke das ist die bessere Lösung, da wir nicht garantieren können, dass die Zertifikate nur für Berliner Router erstellt werden und sehr viele Nutze über die entstandene Ruhe auf der Mailingliste eher glücklich als unglücklich sind.

**Comment by SvenRoederer** [comment]
Meine Stimme für den Lösungsansatz.
Wobei ich mir jetzt auch situationen vorstellen kann, in denen es hilfreich ist über neue Knoten informiert zu werden, wenn man keinen Knoten in der Nähe betreibt. Aber der vorgeschlagenen Ansatz überzeigt durch Datensparsamkeit, auch auf der ML.

**Comment by booo** [comment]
@k-nut Könntest du vielleicht ein Ticket mit unserem Lösungsansatz für die openwifimap erstellen?

Ich schließe das Ticket erstmal.

**Comment by geirkairam** [comment]
Bis es die Lösung mit dieser Karte gibt, glaube ich schon, dass die wöchentliche Information über neue VPN Tunnel auf unserer Liste für manche Menschen interessant wäre.

**Comment by andrenarchy** [comment]
Die map-Lösung finde ich auch richtig gut. Vor allem erfährt man dadurch wirklich von neuen Routern und nicht nur von neuen VPN-Tunneln.

Das feature sollte dann im [neuen Assistenten](https://github.com/freifunk-berlin/firmware-wizard-frontend) und in der openwifimap/libremap implementiert werden. Wer will? :smile:

**Comment by sarumpaet** [comment]
Auf https://hopglass.berlin.freifunk.net sieht man neue Berliner Knoten bereits.

**Comment by sarumpaet** [comment]
Da sich die VPN-Problematik weitgehend erledigt hat und eine "Hallo"-Nachricht besser per Einrichtungsassistent als in der CA generiert wird (und es schon Issues dafür gibt), schließe ich das hier.
