### ISSUE TITLE
Kommentarfeld "Warum möchtest Du den VPN"

### ISSUE THREAD

**Issue by monic2001** [freifunk-berlin/ca.berlin.freifunk.net#28]
Verbindliches Kommentarfeld, warum die Person den VPN des Förderverein freie Netzwerke nutzen möchte

**Comment by SvenRoederer** [comment]
Die Info über das "warum" ist in dre Tat nett. Aber da sie bestimmt nicht bei der Cert-Generierung eine Rolle spielt oder sonstwie ausgewertet wird, lohnt es sich dann diese DAten zu erheben?

**Comment by k-nut** [comment]
Es gibt zwei große Use Cases für das Feld:
- Dem Admin noch mal einen besseren Einblick geben, ob es sich um einen Bot oder echten Menschen handelt und einen Anknüpfpunkt für Gespräche zu geben
- Im Rahmen von #27 auf dem weekly Digest auf der Mailingliste aufnehmen, damit auch der Rest der Community sehen kann, wo neue Installationen gemacht wurden

**Comment by booo** [comment]
Bis jetzt gab es sowohl auf config.berlin als auch auf ca.berlin keine Versuche von Bots IPs bzw. Zertifikate anzufragen. Ein Bot müsste in Zukunft außerdem den Aktivierungslink klicken. Die wenigstens Bots werden daran ein Interesse haben. Und dann gibt es da ja noch ein "Rätzel" im Formular.

Ich will als Admin auch niemanden über die Nutzung des VPNs belehren auf Basis eines Feldes das er/sie ausfüllt. Wir können gerne nochmal auf der Webseite darauf hinweisen, dass die Zertifikate nur im Freifunk-Kontext verwendet werden sollen. Ob dies in Zukunft geschehen wird, kann ich als Admin nicht an einem Feld im Formular feststellen.

Informationen über neue Konten gehören meiner Meinung nach eher in eine ordentliche Karten-Application. Die könnte dann auch Knotenbetreiber_innen über neue Knoten in ihrer Nachbarschaft benachrichtigen.

Ein genriertes Zertifikat heißt auch noch lange nicht, dass die Person dieses für einen Knoten z.B. in Berlin nutzt. Die Zertifikate werden von anderen Communities mitgenutzt u.a. auch für Server.

**Comment by booo** [comment]
Ich sehe nach wie vor keine Notwendigkeit für ein Feld dieser Art.

Da es keine weitere Diskussion gab, schließe ich das Ticket. Bitte öffnet das Ticket oder besprecht das Thema auf der Mailingliste, wenn weiterhin Bedarf an einem solchen Feld besteht.

**Comment by thomasDOTwtf** [comment]
Eine Andere Idee wäre das Kommmentarfeld villeicht in den Maildigest zu integrieren und "meine Nachricht an die Community" zu nennen.

**Comment by geirkairam** [comment]
+1 für Thomas Änderungsvorschlag

**Comment by SvenRoederer** [comment]
ist eine interessante Idee der Umsetzung

**Comment by andrenarchy** [comment]
+1 für die Idee von @thomasDOTde. Allerdings sollte das dann unabhängig von der Key-Generierung laufen, da man das ja auch für Router ohne VPN angeben möchte.

@geirkairam ein Feld 'Nachricht an die community' macht aus meiner Sicht nur Sinn im Assistenten.
