### ISSUE TITLE
Subscribe Mailinglist

### ISSUE THREAD

**Issue by monic2001** [freifunk-berlin/ca.berlin.freifunk.net#29]
- Eine optionale Checkbox, um sich auf der Berliner Mailingliste zu subscriben.
- Bei Check sollte die Bestätigungsmail der Mailingliste versandt werden. 
- Alternativ kann der Bestätigungslink auch in die bestehende Mail des Dienstes integriert werden :)

**Comment by booo** [comment]
Das VPN03 steht mehr als einer Community zur Verfügung. Warum sollten sich Menschen bei der Zertifikatserstellung auf der Mailingliste für Berlin registrieren wollen? Wenn überhaupt gehört das in die IP-Vergabe.

Ich schließe das Ticket. Bitte das Ticket bei der IP-Vergabe wieder eröffnen, wenn weiterhin Bedarf an der Funktion besteht.

**Comment by andrenarchy** [comment]
Ich finde, dass das weder in die IP- noch in die Key-Vergabe gehört.

@monic2001 Wie wäre es, wenn das Häkchen in den neuen Assistenten integriert wird? Wenn du das gut findest, dann eröffne das issue neu unter https://github.com/freifunk-berlin/firmware-wizard-frontend/issues
