### ISSUE TITLE
setup nach Anleitung funktioniert nicht

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/ca.berlin.freifunk.net#33]
ich hab heute mal nach Anleitung meinen Checkout installiert. Das lief alles ohne Fehler durch.
Wenn ich dann den Webserver besuche fliegt mir gleich eine Exception um die Ohren

<pre>
jinja2.exceptions.UndefinedError: 'form' is undefined

Traceback (most recent call last):
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/ca/views.py", line 10, in index
    return render_template('index.html')
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/ca/templates/index.html", line 1, in top-level template code
    {% extends "_layout.html" %}
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/ca/templates/_layout.html", line 29, in top-level template code
    {% block body %}{% endblock %}
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/ca/templates/index.html", line 16, in block "body"
    {{ form.csrf_token }}
  File "/mnt/hosts/build/src/web/freifunk/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
</pre>

**Comment by booo** [comment]
Kannst du mal die Schritte auflisten, die du durchgeführt hast? Ich kann dann versuchen das Problem zu reproduzieren.

**Comment by SvenRoederer** [comment]
auf einem "Ubuntu Trusty" und "Debian 8" probiert:

<pre>
sven@strike:/tmp$ git clone https://github.com/freifunk-berlin/ca.berlin.freifunk.net.git
Klone nach 'ca.berlin.freifunk.net'...
remote: Counting objects: 334, done.
remote: Total 334 (delta 0), reused 0 (delta 0), pack-reused 334
Empfange Objekte: 100% (334/334), 190.05 KiB | 0 bytes/s, Fertig.
Löse Unterschiede auf: 100% (179/179), Fertig.
Prüfe Konnektivität... Fertig.
sven@strike:/tmp$ cd ca.berlin.freifunk.net/
sven@strike:/tmp/ca.berlin.freifunk.net$ virtualenv env -p python3
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in env/bin/python3
Also creating executable in env/bin/python
Installing setuptools, pip...done.
sven@strike:/tmp/ca.berlin.freifunk.net$ . env/bin/activate
(env)sven@strike:/tmp/ca.berlin.freifunk.net$ pip3 install -r requirements.txt
Downloading/unpacking alembic==0.8.2 (from -r requirements.txt (line 1))
  Downloading alembic-0.8.2.tar.gz (931kB): 931kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/alembic/setup.py) egg_info for package alembic
    
    warning: no files found matching '*.jpg' under directory 'docs'
    warning: no files found matching '*.sty' under directory 'docs'
    warning: no files found matching '*.dat' under directory 'tests'
    no previously-included directories found matching 'docs/build/output'
Downloading/unpacking cffi==1.2.1 (from -r requirements.txt (line 2))
  Downloading cffi-1.2.1.tar.gz (335kB): 335kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/cffi/setup.py) egg_info for package cffi
    
Downloading/unpacking cryptography==1.0.1 (from -r requirements.txt (line 3))
  Downloading cryptography-1.0.1.tar.gz (332kB): 332kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking Flask==0.10.1 (from -r requirements.txt (line 4))
  Downloading Flask-0.10.1.tar.gz (544kB): 544kB downloaded                                                                      
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/Flask/setup.py) egg_info for package Flask                        
                                                                                                                                 
    warning: no files found matching '*' under directory 'tests'                                                                 
    warning: no previously-included files matching '*.pyc' found under directory 'docs'                                          
    warning: no previously-included files matching '*.pyo' found under directory 'docs'                                          
    warning: no previously-included files matching '*.pyc' found under directory 'tests'                                         
    warning: no previously-included files matching '*.pyo' found under directory 'tests'                                         
    warning: no previously-included files matching '*.pyc' found under directory 'examples'                                      
    warning: no previously-included files matching '*.pyo' found under directory 'examples'                                      
    no previously-included directories found matching 'docs/_build'                                                              
    no previously-included directories found matching 'docs/_themes/.git'                                                        
Downloading/unpacking Flask-Migrate==1.6.0 (from -r requirements.txt (line 5))                                                   
  Downloading Flask-Migrate-1.6.0.tar.gz                                                                                         
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/Flask-Migrate/setup.py) egg_info for package Flask-Migrate        
                                                                                                                                 
Downloading/unpacking Flask-Script==2.0.5 (from -r requirements.txt (line 6))                                                    
  Downloading Flask-Script-2.0.5.tar.gz (42kB): 42kB downloaded                                                                  
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/Flask-Script/setup.py) egg_info for package Flask-Script          
^[[B^[[B^[[B                                                                                                                     
    warning: no previously-included files matching '*.pyc' found under directory 'docs'                                          
    warning: no previously-included files matching '*.pyo' found under directory 'docs'                                          
    no previously-included directories found matching 'docs/_build'                                                              
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking Flask-SQLAlchemy==2.0 (from -r requirements.txt (line 7))
  Downloading Flask-SQLAlchemy-2.0.tar.gz (93kB): 93kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/Flask-SQLAlchemy/setup.py) egg_info for package Flask-SQLAlchemy
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking idna==2.0 (from -r requirements.txt (line 8))
  Downloading idna-2.0-py2.py3-none-any.whl (61kB): 61kB downloaded
Downloading/unpacking itsdangerous==0.24 (from -r requirements.txt (line 9))
  Downloading itsdangerous-0.24.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/itsdangerous/setup.py) egg_info for package itsdangerous
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking Jinja2==2.8 (from -r requirements.txt (line 10))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Downloading/unpacking Mako==1.0.2 (from -r requirements.txt (line 11))
  Downloading Mako-1.0.2.tar.gz (564kB): 564kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/Mako/setup.py) egg_info for package Mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking MarkupSafe==0.23 (from -r requirements.txt (line 12))
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Downloading/unpacking pyasn1==0.1.8 (from -r requirements.txt (line 13))
  Downloading pyasn1-0.1.8.tar.gz (75kB): 75kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/pyasn1/setup.py) egg_info for package pyasn1
    
Downloading/unpacking pycparser==2.14 (from -r requirements.txt (line 14))
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Downloading/unpacking pyOpenSSL==0.15.1 (from -r requirements.txt (line 15))
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB): 102kB downloaded
Downloading/unpacking python-editor==0.4 (from -r requirements.txt (line 16))
  Downloading python-editor-0.4.tar.gz
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/python-editor/setup.py) egg_info for package python-editor
    
Downloading/unpacking six==1.9.0 (from -r requirements.txt (line 17))
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking SQLAlchemy==1.0.8 (from -r requirements.txt (line 18))
  Downloading SQLAlchemy-1.0.8.tar.gz (4.6MB): 4.6MB downloaded
  Running setup.py (path:/tmp/ca.berlin.freifunk.net/env/build/SQLAlchemy/setup.py) egg_info for package SQLAlchemy
    
    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching '*.mako' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking Werkzeug==0.10.4 (from -r requirements.txt (line 19))
  Downloading Werkzeug-0.10.4-py2.py3-none-any.whl (293kB): 293kB downloaded
Downloading/unpacking wheel==0.24.0 (from -r requirements.txt (line 20))
  Downloading wheel-0.24.0-py2.py3-none-any.whl (63kB): 63kB downloaded
Downloading/unpacking WTForms==2.0.2 (from -r requirements.txt (line 21))
  Downloading WTForms-2.0.2-py2.py3-none-any.whl (128kB): 128kB downloaded
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./env/lib/python3.4/site-packages (from cryptography==1.0.1->-r requirements.txt (line 3))
Installing collected packages: alembic, cffi, cryptography, Flask, Flask-Migrate, Flask-Script, Flask-SQLAlchemy, idna, itsdangerous, Jinja2, Mako, MarkupSafe, pyasn1, pycparser, pyOpenSSL, python-editor, six, SQLAlchemy, Werkzeug, wheel, WTForms
  Running setup.py install for alembic
    
    warning: no files found matching '*.jpg' under directory 'docs'
    warning: no files found matching '*.sty' under directory 'docs'
    warning: no files found matching '*.dat' under directory 'tests'
    no previously-included directories found matching 'docs/build/output'
    Installing alembic script to /tmp/ca.berlin.freifunk.net/env/bin
  Running setup.py install for cffi
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.4/c/_cffi_backend.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-3.4/_cffi_backend.cpython-34m.so
    
  Running setup.py install for cryptography
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/ca.berlin.freifunk.net/env/build/cryptography/pycparser-2.14-py3.4.egg
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    generating cffi module 'build/temp.linux-x86_64-3.4/_padding.c'
    generating cffi module 'build/temp.linux-x86_64-3.4/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-3.4/_openssl.c'
    building '_openssl' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c build/temp.linux-x86_64-3.4/_openssl.c -o build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_openssl.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_openssl.o -lssl -lcrypto -o build/lib.linux-x86_64-3.4/cryptography/hazmat/bindings/_openssl.cpython-34m.so
    building '_constant_time' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c build/temp.linux-x86_64-3.4/_constant_time.c -o build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_constant_time.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_constant_time.o -o build/lib.linux-x86_64-3.4/cryptography/hazmat/bindings/_constant_time.cpython-34m.so
    building '_padding' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c build/temp.linux-x86_64-3.4/_padding.c -o build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_padding.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_padding.o -o build/lib.linux-x86_64-3.4/cryptography/hazmat/bindings/_padding.cpython-34m.so
  Running setup.py install for Flask
    
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
  Running setup.py install for Flask-Migrate
    
  Running setup.py install for Flask-Script
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
  Running setup.py install for Flask-SQLAlchemy
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
  Running setup.py install for itsdangerous
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
  Running setup.py install for Mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
    Installing mako-render script to /tmp/ca.berlin.freifunk.net/env/bin
  Running setup.py install for MarkupSafe
    
    building 'markupsafe._speedups' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c markupsafe/_speedups.c -o build/temp.linux-x86_64-3.4/markupsafe/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/markupsafe/_speedups.o -o build/lib.linux-x86_64-3.4/markupsafe/_speedups.cpython-34m.so
  Running setup.py install for pyasn1
    
  Running setup.py install for pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    Build the lexing/parsing tables
  Running setup.py install for python-editor
    
  Running setup.py install for SQLAlchemy
    building 'sqlalchemy.cprocessors' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c lib/sqlalchemy/cextension/processors.c -o build/temp.linux-x86_64-3.4/lib/sqlalchemy/cextension/processors.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/lib/sqlalchemy/cextension/processors.o -o build/lib.linux-x86_64-3.4/sqlalchemy/cprocessors.cpython-34m.so
    building 'sqlalchemy.cresultproxy' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c lib/sqlalchemy/cextension/resultproxy.c -o build/temp.linux-x86_64-3.4/lib/sqlalchemy/cextension/resultproxy.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/lib/sqlalchemy/cextension/resultproxy.o -o build/lib.linux-x86_64-3.4/sqlalchemy/cresultproxy.cpython-34m.so
    building 'sqlalchemy.cutils' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/ca.berlin.freifunk.net/env/include/python3.4m -c lib/sqlalchemy/cextension/utils.c -o build/temp.linux-x86_64-3.4/lib/sqlalchemy/cextension/utils.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/lib/sqlalchemy/cextension/utils.o -o build/lib.linux-x86_64-3.4/sqlalchemy/cutils.cpython-34m.so
    
    warning: no files found matching '*.jpg' under directory 'doc'
    warning: no files found matching '*.mako' under directory 'doc'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'sa2to3.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Successfully installed alembic cffi cryptography Flask Flask-Migrate Flask-Script Flask-SQLAlchemy idna itsdangerous Jinja2 Mako MarkupSafe pyasn1 pycparser pyOpenSSL python-editor six SQLAlchemy Werkzeug wheel WTForms
Cleaning up...
(env)sven@strike:/tmp/ca.berlin.freifunk.net$ cp config.py instance/
(env)sven@strike:/tmp/ca.berlin.freifunk.net$ cp config.py instance/
 # sonst gibt's error "FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/tmp/ca.berlin.freifunk.net/instance/config.py'"
(env)sven@strike:/tmp/ca.berlin.freifunk.net$ ./manage.py db init
  Creating directory /tmp/ca.berlin.freifunk.net/migrations ... done
  Creating directory /tmp/ca.berlin.freifunk.net/migrations/versions ... done
  Generating /tmp/ca.berlin.freifunk.net/migrations/README ... done
  Generating /tmp/ca.berlin.freifunk.net/migrations/alembic.ini ... done
  Generating /tmp/ca.berlin.freifunk.net/migrations/env.py ... done
  Generating /tmp/ca.berlin.freifunk.net/migrations/script.py.mako ... done
  Please edit configuration/connection/logging settings in '/tmp/ca.berlin.freifunk.net/migrations/alembic.ini' before proceeding.
(env)sven@strike:/tmp/ca.berlin.freifunk.net$ ./manage.py db migrate
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'request'
  Generating /tmp/ca.berlin.freifunk.net/migrations/versions/c307c2078e_.py ... done
(env)sven@strike:/tmp/ca.berlin.freifunk.net$ ./manage.py db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c307c2078e, empty message
(env)sven@strike:/tmp/ca.berlin.freifunk.net$ python3 manage.py runserver -d
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
</pre>

**Comment by k-nut** [comment]
Da war ein Bug im Code. Scheinbar noch von unserem Refactoring / Reorganisation des Codes. #34 sollte das beheben.

**Comment by SvenRoederer** [comment]
#34 scheint erstmal zu helfen
