### ISSUE TITLE
reduce size of cert-files by removing textual-representation

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/ca.berlin.freifunk.net#36]
the certificates are sent out in PEM-encoded version and also textual representation of the cert.

the textual version is only useful to be read by human, removing this part saves more than 2500 bytes in jffs

**Comment by booo** [comment]
Any idea how to configure this with easy-rsa?

**Comment by booo** [comment]
I can add a `openssl x509 -in freifunk_client.crt -out freifunk_client.crt` to the script.

**Comment by SvenRoederer** [comment]
don't know on easyras, but maybe some "sed" or "grep" on the result.

**Comment by SvenRoederer** [comment]
current code of /etc/openvpn/clients/openvpn-build-key after cert + key is generated:

> mkdir ${OUTDIR}/freifunk_${NAME}
> cp -au ${KEYDIR}/freifunk-ca.crt ${OUTDIR}/freifunk_${NAME}/
> cp -au ${KEYDIR}/freifunk_${NAME}.crt ${OUTDIR}/freifunk_${NAME}/
> cp -au ${KEYDIR}/freifunk_${NAME}.key ${OUTDIR}/freifunk_${NAME}/

when changing to 

> mkdir ${OUTDIR}/freifunk_${NAME}
> cp -au ${KEYDIR}/freifunk-ca.crt ${OUTDIR}/freifunk_${NAME}/
> cat ${KEYDIR}/freifunk_${NAME}.crt | openssl x509 -outform pem >${OUTDIR}/freifunk_${NAME}/freifunk_${NAME}.crt 
> cp -au ${KEYDIR}/freifunk_${NAME}.key ${OUTDIR}/freifunk_${NAME}/

the result contains only the cert in PEM-format. 
I think it will be ok to ignore the "-a -u"-options of cp

**Comment by SvenRoederer** [comment]
@boo, not sure how openssl will handle read and write to the same file. 
But your approach is very the same as my approach. my lines are tested on a sample-cert

**Comment by booo** [comment]
I tested it with the command I posted and it seems to work.

**Comment by booo** [comment]
The tar for the user contains now a striped cert.
