### ISSUE TITLE
Hinweis bzgl. Bearbeitungsdauer und eine kurze Bestätigungsmail.

### ISSUE THREAD

**Issue by willwach** [freifunk-berlin/ca.berlin.freifunk.net#41]
Ich fände es sinnvoll auf der Seite "http://ca.berlin.freifunk.net/" einen Hinweis unterzubringen, wie lange man sich gedulden soll, bevor man nachfragt oder erneut versucht einen Zugang anzufordern.

1 oder 2 Wochen wären völlig ok wenn man weiß das es so lange dauern kann.
Und eventuell beantragt man dann auch schon etwas früher wenn man weiß, das man in drei Wochen Zeit hat um einen Router einzurichten.

Eine Bestätigungsmail wäre auch nicht schlecht. Die Anforderung wird zwar auf der Seite bestätigt wenn erfolgreich, aber eine Email kann man auch später nochmal konsultieren und es gibt einem das Gefühl das im Hintergrund etwas passiert ist.

Man vermeidet Mehrfachanforderungen aus Ungeduld oder Verunsicherung.
Man vermeidet Nachfragen.

**Comment by booo** [comment]
Eine ähnliche Idee war im Gespräch mit @KenTacki entstanden.

Hättest du Lust einen Text für die Bestätigungsmail zu formulieren. [Hier](https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/ca/templates/mail.txt) findest du den Text für die finale Mail.

Wie man Mails versendet kann man sich [hier](https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/manage.py#L30) abgucken.

Wenn es einen Entwurf für die Bestätigungsmail gibt, kann ich diesen auch integrieren, wenn du dich nicht mit Python beschäftigen willst/kannst.

**Comment by willwach** [comment]
Ich schaue mir das morgen mal an. Der Mailtext sollte kein Problem sein. 
Vermutlich bekomme ich auch noch die Methode hin, die das ganze versendet.
Aber in den Workflow müsste das dann jemand anderes einbauen.

Wie testet ihr das auf Funktionalität? 
Ich möchte mir jetzt nicht unbedingt den Code hier installieren?
