### ISSUE TITLE
Track migrations in git

### ISSUE THREAD

**Issue by k-nut** [freifunk-berlin/ca.berlin.freifunk.net#45]
Is there a reason why we do not include the `migrations` folder in git? Since it contains all the versions and the instructions on how to run the migrations I think we should include it.

**Comment by SvenRoederer** [comment]
see https://github.com/freifunk-berlin/ca.berlin.freifunk.net/issues/15

**Comment by k-nut** [comment]
And I did take a look at the open issues before I opened this. I don't know how it was possible for me to miss this :D
