### ISSUE TITLE
An option to reject and suspend creation of certificates is required

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/ca.berlin.freifunk.net#50]
recently we had some certificate-requests where I was in contact with the requestor and "paused" their processing.
in the mean time some other admin signed some of these requests before the issues (unclear email) was resolved.

adding a status-flag and a comment-field for hold / reject seems helpfull

**Comment by SvenRoederer** [comment]
see https://lists.berlin.freifunk.net/pipermail/berlin/2017-January/035009.html for a request of request-revocation (aka reject) ...

**Comment by SvenRoederer** [comment]
for reject see PR #52

**Comment by SvenRoederer** [comment]
for suspend:
- add a new table with pkey referencing to "ID"
- have a "comment" field, for a short description why the request is suspended

* on reach precessing-run do the "normal" requests at first, then iterate over the suspended table for 
  * sign
  * reject
  * update comment

**Comment by booo** [comment]
I suggest that we just reject the request by removing it from the request table and send the user a nice mail about the rejection.

**Comment by SvenRoederer** [comment]
Reject-feature was "merged commit 46e84eb into master on 10 Jun"
