### ISSUE TITLE
move BBBVPN management into a separate instance

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/ca.berlin.freifunk.net#51]
Wollen wir die BBBVPN CA auf eine separate Instanz dieses Tools umstellen?

das spart Wartungs- und Rechner-ressourcen.
wir brauchen den aktuelle Code nur um eine konfigurierbare "autoapprove"-funktion erweitern.

@sven-ola

**Comment by booo** [comment]
Würde ich nicht machen, da es uns nur Arbeit erzeugt.

Ich schlage vor, dass wir uns zum BBBVPN mal grundsätzlich Gedanken machen und es auf ein Tunnellösung umstellen, die keine Zertifikate erfordert. Wenn wir das BBBVPN als Peering-Punkt verstehen, sehe ich keine Notwendigkeit einzelne Peers auszuschließen.

**Comment by SvenRoederer** [comment]
wenn wir den CA-Code nicht für noch was anderes als VPN03 nutzen wollen, können wir die Arbeit dran auch einstellen. Denn nur für's abgekündigte VPN03 lohnt sich kein Aufwand.

Dann mach mal ein Issue + Padseite / Wiki für BBB-VPNv2 auf :)

**Comment by booo** [comment]
Ich sehe auch keinen erhöhten Bedarf weitere Feature zu implementieren, da der CA-Code seinen Dienst ganz gut tut. Das VPN03 wird uns noch länger begleiten. "Kleinere" Optimierungen können also durch aus sinnvoll sein.

Ich habe gerade kein gesteigertes Interesse am BBBVPNv2. Wenn du gesteigertes Interesse hast, wärm doch einfach mal einen alten Thread zum Thema auf.

**Comment by SvenRoederer** [comment]
Warum nicht das BBB-VPN durch einen anderen Tunnel ersetzen.
Das hilft dann hoffentlich auch bei unserem OLSR-problem das wir dadurch im Moment haben.

**Comment by SvenRoederer** [comment]
Da wir BBB-VPN jetzt via tunneldigger machen und die BBB-VPN OpenVPN-Lösung deprecated ist, kann das Issue nun endlich zu.
