### ISSUE TITLE
Add link to source code to introduce community into the development

### ISSUE THREAD

**Issue by niccokunzmann** [freifunk-berlin/ca.berlin.freifunk.net#54]
**Goal**  
When I visit the [main page](http://ca.berlin.freifunk.net/), I would like to see a link to the source code. This allows me to connect better to the developers, propose ideas and get help implementing them.

**Proposal**  
I propose the following sentence:

> ca.berlin.freifunk.net wird von der Berliner Freifunk Gemeinschaft [auf GitHub](https://github.com/freifunk-berlin/ca.berlin.freifunk.net) entwickelt. Du kannst mithelfen und die Software verbessern.

**Hints**  
To solve this issue, the sentence can be included into the [_layout](https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/ca/templates/_layout.html#L33) file at the bottom.

**Comment by SvenRoederer** [comment]
@niccokunzmann  can you create a PR for this?
