### ISSUE TITLE
move configuration into configuration file

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/ca.berlin.freifunk.net#6]
We should move all configurable parameters into a configuration file like config.py

**Comment by k-nut** [comment]
So that file would contain:
- sqlite path
- the app's secret key
- COMMAND_BUILD
- COMMAND_MAIL
- path to directoy containing old certificates

anything else?

**Comment by booo** [comment]
No, I think that's all.

**Comment by k-nut** [comment]
I have some positive experience with using environment variables instead of a config.py file. Those could then be set by hand before calling the script or by loading them from a (python agnostic) shell file. 
But we could also just create a config.py. What would you prefer?

**Comment by booo** [comment]
My initial idea was something like this: https://github.com/freifunk-berlin/config.berlin.freifunk.net/blob/master/config.cfg.dist

We do not have a shell file where we can put some env variables. uwsgi starts the app:

https://github.com/freifunk-berlin/puppet/blob/ca.berlin.freifunk.net/puppet/manifests/site.pp#L321

Maybe there is a env option for the uwsgi script?

**Comment by booo** [comment]
Maybe we should take a look at this: https://exploreflask.com/configuration.html

**Comment by booo** [comment]
I implemented a solution where we have a config.py in the root directory. You can overwrite the default configuration by adding a `instance/config.py` file.
